services:
  kibana:
    image: ${KIBANA_IMAGE:-docker.elastic.co/kibana/kibana:7.17.22}
    container_name: ${CONTAINER_PREFIX:-stack-orchestra}-kibana
    environment:
      - ELASTICSEARCH_HOSTS=${KIBANA_ELASTICSEARCH_HOSTS:-http://elasticsearch:9200}
    ports:
      - "${KIBANA_PORT:-5601}:5601"
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:5601/api/status >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - ${NETWORK_NAME:-stack-orchestra}

