services:
  mongodb:
    image: ${MONGODB_IMAGE:-mongo:7.0}
    container_name: ${CONTAINER_PREFIX:-stack-orchestra}-mongodb
    command: ["--wiredTigerCacheSizeGB", "1"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME:-orchestra}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD:-orchestra}
    volumes:
      - mongodb-data:/data/db
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "mongodb://${MONGODB_ROOT_USERNAME:-orchestra}:${MONGODB_ROOT_PASSWORD:-orchestra}@localhost:27017/admin",
          "--eval",
          "db.runCommand({ ping: 1 })",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - ${NETWORK_NAME:-stack-orchestra}

