services:
  mysql:
    image: mysql:8.0
    container_name: stack-orchestra-mysql
    command:
      [
        "--default-authentication-plugin=mysql_native_password",
        "--innodb-buffer-pool-size=256M",
      ]
    environment:
      MYSQL_DATABASE: stack_orchestra
      MYSQL_USER: orchestra
      MYSQL_PASSWORD: orchestra
      MYSQL_ROOT_PASSWORD: mysqlroot
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - stack-orchestra

