services:
  neo4j:
    image: ${NEO4J_IMAGE:-neo4j:5.23}
    container_name: ${CONTAINER_PREFIX:-stack-orchestra}-neo4j
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH:-neo4j/${NEO4J_PASSWORD:-stackorchestra}}
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_default__advertised__address=localhost
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
    ports:
      - "${NEO4J_HTTP_PORT:-7474}:7474"
      - "${NEO4J_BOLT_PORT:-7687}:7687"
    healthcheck:
      test:
        [
          "CMD",
          "cypher-shell",
          "-u",
          "neo4j",
          "-p",
          "${NEO4J_PASSWORD:-stackorchestra}",
          "RETURN 1;",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - ${NETWORK_NAME:-stack-orchestra}

