services:
  neo4j:
    image: neo4j:5.23
    container_name: stack-orchestra-neo4j
    environment:
      - NEO4J_AUTH=neo4j/stackorchestra
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_default__advertised__address=localhost
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
    ports:
      - "7474:7474"
      - "7687:7687"
    healthcheck:
      test:
        [
          "CMD",
          "cypher-shell",
          "-u",
          "neo4j",
          "-p",
          "stackorchestra",
          "RETURN 1;",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - stack-orchestra

