services:
  nginx:
    image: nginx:1.27-alpine
    container_name: stack-orchestra-nginx
    volumes:
      - ./ops/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - stack-orchestra

