services:
  postgres:
    image: ${POSTGRES_IMAGE:-postgres:16}
    container_name: ${CONTAINER_PREFIX:-stack-orchestra}-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-stack_orchestra}
      POSTGRES_USER: ${POSTGRES_USER:-orchestra}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-orchestra}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - ${NETWORK_NAME:-stack-orchestra}

