services:
  qdrant:
    image: ${QDRANT_IMAGE:-qdrant/qdrant:v1.7.4}
    container_name: ${CONTAINER_PREFIX:-stack-orchestra}-qdrant
    ports:
      - "${QDRANT_HTTP_PORT:-6333}:6333"  # REST API
      - "${QDRANT_GRPC_PORT:-6334}:6334"  # gRPC
    volumes:
      - qdrant-data:/qdrant/storage
    environment:
      QDRANT__SERVICE__GRPC_PORT: ${QDRANT_GRPC_PORT:-6334}
      QDRANT__SERVICE__HTTP_PORT: ${QDRANT_HTTP_PORT:-6333}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - ${NETWORK_NAME:-stack-orchestra}

