services:
  redis:
    image: ${REDIS_IMAGE:-redis:7.4-alpine}
    container_name: ${CONTAINER_PREFIX:-stack-orchestra}-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - ${NETWORK_NAME:-stack-orchestra}

