services:
  scylla:
    image: ${SCYLLA_IMAGE:-scylladb/scylla:latest}
    container_name: ${CONTAINER_PREFIX:-stack-orchestra}-scylla
    command:
      - --smp
      - "1"
      - --memory
      - "1G"
      - --overprovisioned
      - --api-address
      - "0.0.0.0"
      - --developer-mode
      - "1"
    volumes:
      - scylla-data:/var/lib/scylla
    ports:
      - "${SCYLLA_CQL_PORT:-9042}:9042"
      - "${SCYLLA_REST_PORT:-10000}:10000"
      - "${SCYLLA_INTER_NODE_PORT:-7000}:7000"
      - "${SCYLLA_INTER_NODE_TLS_PORT:-7001}:7001"
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep -E '^UN' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    networks:
      - ${NETWORK_NAME:-stack-orchestra}

