services:
  scylla:
    image: scylladb/scylla:latest
    container_name: stack-orchestra-scylla
    command:
      - --smp
      - "1"
      - --memory
      - "1G"
      - --overprovisioned
      - --api-address
      - "0.0.0.0"
      - --developer-mode
      - "1"
    volumes:
      - scylla-data:/var/lib/scylla
    ports:
      - "9042:9042"
      - "10000:10000"
      - "7000:7000"
      - "7001:7001"
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep -E '^UN' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    networks:
      - stack-orchestra

